### ISSUE TITLE
Consider updated binding format allowing multiple application-specific backends

### ISSUE THREAD

**Issue by vzhabko** [pivotal-cf/spring-cloud-vault-connector#11]
The issue is how backends map defined in VaultServiceInfo. It expects single string to be returned on get for "generic" key. However, Vault service broker returns array of generic/transit backends:
```javascript
 "backends": {
	"generic": [
		"cf/7f1a12a9-4a52-4151-bc96-874380d30182/secret",
		"cf/c4073566-baee-48ae-88e9-7c7c7e0118eb/secret"
	],
	"transit": [
		"cf/7f1a12a9-4a52-4151-bc96-874380d30182/transit",
		"cf/c4073566-baee-48ae-88e9-7c7c7e0118eb/transit"
	]
}
```

This will result in class cast exception ArrayList vs String when in line 181 of VaultConnectorBootstrapConfiguration.
Current implementation of VaultServiceInfo.backends

```
private final Map<String, String> backends;
```

Should be changed to 

```
private final Map<String, List<String>> backends;
```
I have fix for that, I am looking for advice how to provide it.

Thank you,
Vasyl

**Comment by mp911de** [comment]
Thanks for reporting the issue. We should fix the issue and make sure that single-valued and multi-valued bindings are considered properly. That being said, happy to review your pull request.

**Comment by mp911de** [comment]
See also #12.

**Comment by mp911de** [comment]
The cause that requires a change is not a bug but it is an enhancement to vault-service-broker that allows multiple backends, relabelling this ticket as enhancement.

**Comment by mp911de** [comment]
Care to verify whether the current `2.1.0.BUILD-SNAPSHOT` works for you? If so, then I can prepare a milestone release.

**Comment by vzhabko** [comment]
Hi Mark,

I have 2.1.0.BUILD-SNAPSHOT tested in our staging PCF instance it is working as expected.

Thank you,
Vasyl
