### ISSUE TITLE
Example on how to access vault values from spring boot application!

### ISSUE THREAD

**Issue by MichaelLoveUSA** [pivotal-cf/spring-cloud-vault-connector#7]
Hi there - we are trying to use the vault cloudfoundry connector in a spring boot app that we created and we can't see how to actually get a value from a vault key we have created. Do you have any examples of how to do that? We are able to get the service info.

```
<dependency>
	<groupId>io.pivotal.spring.cloud</groupId>
	<artifactId>spring-cloud-vault-cloudfoundry-connector</artifactId>
	<version>1.0.0.RC1</version>
</dependency>
```

**Comment by mp911de** [comment]
Take a look here: https://github.com/mp911de/spring-cloud-vault-config-samples/tree/master/spring-cloud-vault/cloudfoundry

**Comment by mp911de** [comment]
Perhaps of interest, too: https://github.com/spring-cloud/spring-cloud-vault/issues/183

**Comment by mp911de** [comment]
Closing this one as the question is answered.
